### ISSUE TITLE
Segmentation fault when running (Python examples) with overlapping option.

### ISSUE THREAD

**Issue by IwoHerka** [mapequation/infomap#10]
Hi,

I've been messing around with examples in Python and managed to cause seg-fault.
When running default example for NetworkX (`example-networkx.py`) but with `--overlapping` option
this happens:

```
=======================================================
  Infomap v0.19.0 starts at [2017-06-10 16:00:52]
  -> Configuration: overlapping
                    two-level
  -> Use undirected flow and 2nd order Markov dynamics
=======================================================
Building Infomap network from a NetworkX graph...
Find communities with Infomap...
Finalizing network...
Segmentation fault (core dumped)
```

My GCC version: `gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005`

Cheers!

**Comment by yohm** [comment]
I found a similar problem also in C++. When I edit `examples/cpp/minimal/example.cpp` as follows, a bus error occurs

```diff
-       infomap::Infomap infomapWrapper("--two-level -N2");
+       infomap::Infomap infomapWrapper("--two-level -N2 --overlapping");
```

```
=======================================================
  Infomap v0.19.5 starts at [2017-08-05 16:46:14]
  -> Configuration: overlapping
                    two-level
                    num-trials = 2
  -> Use undirected flow and 2nd order Markov dynamics
=======================================================
Finalizing network...
zsh: bus error  ./example
```

**Comment by danieledler** [comment]
Thanks for the feedback, the problem was that the `--overlapping` flag creates a memory network but in the library that required the class `infomap::MemInfomap` instead of `infomap::Infomap`. (The bus error is due to calling a function that is only defined for a memory network so the address didn't make sense)

This is solved now by using a memory network implicitly, so the code above should work without changing `Infomap` to `MemInfomap`.

**Comment by isukrit** [comment]
I don't know if I am doing something really stupid (chances are, I am not since the code works perfectly fine without the overlapping option), but I am still getting the same error. I am using the latest repo from GitHub. Any insights, Daniel? The network is weighted and has less than 300 nodes.

Output trace, FYI:
  Infomap v0.19.0 starts at [2017-09-20 19:45:41]
  -> Configuration: overlapping
                    zero-based-numbering
                    num-trials = 10
  -> Use undirected flow and 2nd order Markov dynamics

**Comment by danieledler** [comment]
Good that you provided the output @isukrit, as it shows the problem. The compiled version you are running is apparently version 0.19.0, so probably you have just forgotten to run `make` after pulling in the new code? The solution for this issue is in v0.19.11.

**Comment by isukrit** [comment]
Yes, I did not make the code in the examples directory. Making it in examples directory solved the issue. Thanks for your time.
